# Project information
site_name: TIM MkDocs
site_author: 'Jean-François Cartier'
site_description: >-
  Wiki des cours en TIM version jfcartier
copyright: TIM

# Repository
# repo_name: 'jfcmontmorency/jfcmontmorency.github.io'
# repo_url: 'https://github.com/jfcmontmorency/jfcmontmorency.github.io'

# Navigation
nav:
  - Home: index.md

# Theme (Material de Google)
theme:
  name: material
  language: fr
  logo: logo.svg
  favicon: logo.svg
  features:
    - content.tooltips
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Mode sombre
        
# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

# Extras
extra:
  generator: false
