# Project information
site_name: TIM MkDocs
site_author: 'Jean-François Cartier'
site_description: >-
  Wiki des cours en TIM version jfcartier

# Repository
repo_name: 'jfcmontmorency/jfcmontmorency.github.io'
repo_url: 'https://github.com/jfcmontmorency/jfcmontmorency.github.io'

# Theme
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.sections
  icon:
    logo: logo

# Plugins
plugins:
  - projects:
      projects_dir: cours
      # projects_config_transform: !!python/name:cours.transform
      # log_level: info

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
