site_name: Wiki
site_description: 'Wiki - jfcartier'
site_author: 'Jean-François Cartier'
docs_dir: docs/
repo_name: 'jfcmontmorency/jfcmontmorency.github.io'
repo_url: 'https://github.com/jfcmontmorency/jfcmontmorency.github.io'
nav:
    - Web 3:
        - Accueil: 582_311_MO/index.md
    - Stage:
        - Accueil: 582_611_MO/index.md
theme:
  name: 'material'
plugins:
  - projects:
      projects_dir: cours
      projects_config_transform: !!python/name:cours.transform
      log_level: info
